export enum AUTH_SAGA_ACTIONS {
  GOOGLE_SIGN_IN_SAGA = 'authSaga/GOOGLE_SIGN_IN_SAGA',
  FACEBOOK_SIGN_IN_SAGA = 'authSaga/FACEBOOK_SIGN_IN_SAGA',
  SIGN_OUT_SAGA = 'authSaga/SIGN_OUT_SAGA',
  CREATE_CHANNEL_SAGA = 'authSaga/CREATE_CHANNEL_SAGA',
}
