export enum AUTH_SAGA_ACTION {
  CHECK_USER = 'authSaga/CHECK_USER',
  SYNC_USER_TASK_LISTS = 'authSaga/SYNC_USER_TASK_LISTS',
  GOOGLE_SIGN_IN = 'authSaga/GOOGLE_SIGN_IN',
  FACEBOOK_SIGN_IN = 'authSaga/FACEBOOK_SIGN_IN',
  SIGN_OUT = 'authSaga/SIGN_OUT',
  DELETE_ACCOUNT = 'authSaga/DELETE_ACCOUNT',
  CREATE_CHANNEL = 'authSaga/CREATE_CHANNEL',
}
