export enum AUTH_SAGA_ACTIONS {
  CHECK_USER = 'authReducer/CHECK_USER',
  SYNC_USER_TASK_LISTS = 'authReducer/SYNC_USER_TASK_LISTS',
  GOOGLE_SIGN_IN_SAGA = 'authSaga/GOOGLE_SIGN_IN_SAGA',
  FACEBOOK_SIGN_IN_SAGA = 'authSaga/FACEBOOK_SIGN_IN_SAGA',
  SIGN_OUT_SAGA = 'authSaga/SIGN_OUT_SAGA',
  CREATE_CHANNEL_SAGA = 'authSaga/CREATE_CHANNEL_SAGA',
}
