export enum SIGN_IN_SAGA_ACTIONS {
  GET_GOOGLE_USER_DATA_SAGA = 'signInSaga/GET_GOOGLE_USER_DATA_SAGA',
  GOOGLE_SIGN_OUT_SAGA = 'signInSaga/GOOGLE_SIGN_OUT_SAGA',
  GET_FACEBOOK_USER_DATA_SAGA = 'signInSaga/GET_FACEBOOK_USER_DATA_SAGA',
  FACEBOOK_SIGN_OUT_SAGA = 'signInSaga/FACEBOOK_SIGN_OUT_SAGA',
}
