export enum TASKS_SAGA_ACTION {
  ADD_NEW_TASK_LIST = 'tasksSaga/ADD_NEW_TASK_LIST',
  ADD_NEW_TASK = 'tasksSaga/ADD_NEW_TASK',
  EDIT_TASK_LIST_TITLE = 'tasksSaga/EDIT_TASK_LIST_TITLE',
  DELETE_TASK_LIST_FULL = 'tasksSaga/DELETE_TASK_LIST_FULL',
  DELETE_TASK_LIST_FROM_SCREEN = 'tasksSaga/DELETE_TASK_LIST_FROM_SCREEN',
  SET_TASK_IS_DONE = 'tasksSaga/SET_TASK_IS_DONE',
  SET_EDITED_TASK = 'tasksSaga/SET_EDITED_TASK',
  WAIT_CLOSE_TASK_HORIZONTAL_MENU = 'tasksSaga/WAIT_CLOSE_TASK_HORIZONTAL_MENU',
  CLOSE_TASK_HORIZONTAL_MENU = 'tasksSaga/CLOSE_TASK_HORIZONTAL_MENU',
  DELETE_TASK = 'tasksSaga/DELETE_TASK',
}
