export enum TASKS_ACTIONS {
  SET_TASK_LISTS = 'taskListsReducer/SET_TASK_LISTS',
  ADD_NEW_TASK_LIST = 'taskListsReducer/ADD_NEW_TASK_LIST',
  ADD_NEW_TASK = 'taskListsReducer/ADD_NEW_TASK',
  ADD_TASK_NOTIFICATION = 'taskListsReducer/ADD_TASK_NOTIFICATION',
  EDIT_TASK_LIST_TITLE = 'taskListsReducer/EDIT_TASK_LIST_TITLE',
  DELETE_TASK_LIST_FROM_SCREEN = 'taskListsReducer/DELETE_TASK_LIST_FROM_SCREEN',
  DELETE_TASK_LIST_FULL = 'taskListsReducer/DELETE_TASK_LIST_FULL',
  SET_TASK_DONE = 'taskListsReducer/SET_TASK_DONE',
  EDIT_TASK_TITLE = 'taskListsReducer/EDIT_TASK_TITLE',
  DELETE_TASK = 'taskListsReducer/DELETE_TASK',
}
