export enum USER_SAGA_ACTION {
  CHECK_USER = 'userSaga/CHECK_USER',
  CHANGE_LANGUAGE = 'userSaga/CHANGE_LANGUAGE',
  CHANGE_ACCENT_COLOR = 'userSaga/CHANGE_DARK_MODE',
  CHANGE_DARK_MODE = 'userSaga/CHANGE_THEME',
  SYNC_USER_DATA = 'userSaga/SYNC_USER_DATA',
  GOOGLE_SIGN_IN = 'userSaga/GOOGLE_SIGN_IN',
  FACEBOOK_SIGN_IN = 'userSaga/FACEBOOK_SIGN_IN',
  SIGN_OUT = 'userSaga/SIGN_OUT',
  DELETE_ACCOUNT = 'userSaga/DELETE_ACCOUNT',
  CREATE_CHANNEL = 'userSaga/CREATE_CHANNEL',
  GET_USER_DATA = 'userSaga/GET_USER_DATA',
  CONTACT_THE_AUTHOR = 'userSaga/CONTACT_THE_AUTHOR',
}
