export enum USER_REDUCER_ACTION {
  SET_USER_DATA = 'userReducer/SET_USER_DATA',
  SET_AUTH_STATE = 'userReducer/SET_AUTH_STATE',
  SET_CHANNEL_ID = 'userReducer/SET_CHANNEL_ID',
  SET_LANGUAGE = 'userReducer/SET_LANGUAGE',
  SET_PROVIDER_ID = 'userReducer/SET_PROVIDER_ID',
  SET_USER_AVATAR = 'userReducer/SET_USER_AVATAR',
  SET_THEME = 'userReducer/SET_THEME',
  SET_ACCENT_COLOR = 'userReducer/SET_ACCENT_COLOR',
  SET_ERROR_MODAL_MESSAGE = 'userReducer/SET_ERROR_MODAL_MESSAGE',
}
