export enum USER_SAGA_ACTION {
  CHECK_USER = 'userSaga/CHECK_USER',
  CHANGE_LANGUAGE = 'userSaga/CHANGE_LANGUAGE',
  SYNC_USER_TASK_LISTS = 'userSaga/SYNC_USER_TASK_LISTS',
  GOOGLE_SIGN_IN = 'userSaga/GOOGLE_SIGN_IN',
  FACEBOOK_SIGN_IN = 'userSaga/FACEBOOK_SIGN_IN',
  SIGN_OUT = 'userSaga/SIGN_OUT',
  DELETE_ACCOUNT = 'userSaga/DELETE_ACCOUNT',
  CREATE_CHANNEL = 'userSaga/CREATE_CHANNEL',
  GET_USER_DATA = 'userSaga/GET_USER_DATA',
}
