import { COLORS } from '@colors/colors';
import { ThemeType } from '@store/reducers/userReducer/types';

export const lightTheme: ThemeType = {
  darkMode: false,
  BACKGROUND_COLOR: COLORS.GALLERY,
  MODAL_BACKGROUND_COLOR: COLORS.GALLERY,
  TEXT_COLOR: COLORS.BLACK,
  PLACEHOLDER_COLOR: COLORS.ALTO2,
  TASK_LIST_COLOR: COLORS.ALTO2,
  TASK_COLOR: COLORS.SILVER_CHALICE2,
  ICON_BUTTON_COLOR: COLORS.SHARK,
  TAB_BAR_ICON_COLOR: COLORS.TUNDORA,
  TAB_BAR_TEXT_COLOR: COLORS.SHARK,
  TAB_BAR_BACKGROUND_COLOR: COLORS.WHITE,
  SUBTEXT_COLOR: COLORS.EMPEROR,
};

export const darkTheme: ThemeType = {
  darkMode: true,
  BACKGROUND_COLOR: COLORS.SHARK2,
  MODAL_BACKGROUND_COLOR: COLORS.SHARK1,
  TEXT_COLOR: COLORS.WHITE,
  PLACEHOLDER_COLOR: COLORS.DOVE_GRAY,
  TASK_LIST_COLOR: COLORS.WOODSMOKE2,
  TASK_COLOR: COLORS.MINE_SHAFT1,
  ICON_BUTTON_COLOR: COLORS.SILVER_CHALICE1,
  TAB_BAR_ICON_COLOR: COLORS.MANATEE,
  TAB_BAR_TEXT_COLOR: COLORS.DOVE_GRAY,
  TAB_BAR_BACKGROUND_COLOR: COLORS.WOODSMOKE2,
  SUBTEXT_COLOR: COLORS.MANATEE,
};
